// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCVHoFawqBmBCE7UYwjq-tgv1K-iqjcA',
    appId: '1:976696250264:web:ad9e65a54d95d7430725ed',
    messagingSenderId: '976696250264',
    projectId: 'todo-app-2273a',
    authDomain: 'todo-app-2273a.firebaseapp.com',
    storageBucket: 'todo-app-2273a.appspot.com',
    measurementId: 'G-SF8L58SX1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29LWKslBeT_xBQNm7VsRZ8yQuvNtliBM',
    appId: '1:976696250264:android:96f0691874dfba8d0725ed',
    messagingSenderId: '976696250264',
    projectId: 'todo-app-2273a',
    storageBucket: 'todo-app-2273a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrHQBVCxIyKwo_QWled1hUCrDMes5tMc',
    appId: '1:976696250264:ios:2004d46eee9eb5fb0725ed',
    messagingSenderId: '976696250264',
    projectId: 'todo-app-2273a',
    storageBucket: 'todo-app-2273a.appspot.com',
    iosClientId: '976696250264-jr4eefje9nosifuvj6qfdbndouaq866n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrHQBVCxIyKwo_QWled1hUCrDMes5tMc',
    appId: '1:976696250264:ios:2004d46eee9eb5fb0725ed',
    messagingSenderId: '976696250264',
    projectId: 'todo-app-2273a',
    storageBucket: 'todo-app-2273a.appspot.com',
    iosClientId: '976696250264-jr4eefje9nosifuvj6qfdbndouaq866n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
